name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.2
    - name: Install dependencies
      run: dotnet tool restore
    - name: Build
      run: dotnet fornax build
    - name: Upload
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0 
      with:
        source_dir: '_public'
        container_name: '$web'
        connection_string: ${{ secrets.ConnectionString }}
        sync: true
      
      
